apps/voto/urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import login, logout_then_login

urlpatterns = [
	url(r'^login/$',login,{'template_name':'voto/login.html'}, name='login'),
	url(r'^logout/$', logout_then_login, name='logout'),
	url(r'^$',index_view,name='index_view'),
	url(r'^registro_usuario/$',registro_usuario.as_view(),name='registro_usuario'),
	url(r'^crear_pregunta/$',crear_pregunta,name='crear_pregunta'),
	url(r'^anadir_opciones/$',anadir_opciones,name='anadir_opciones'),
	url(r'^contestar_pregunta/(?P<pk>[-\w]+)/$',contestar_pregunta,name='contestar_pregunta'),
]

urls.py
from django.conf.urls import url
from .views import *
from django.contrib.auth.views import login, logout_then_login
from django.contrib.auth.decorators import login_required

urlpatterns = [
	url(r'^login/$',login,{'template_name':'voto/login.html'}, name='login'),
	url(r'^logout/$', logout_then_login, name='logout'),
	url(r'^$',index_view,name='index_view'),
	url(r'^registro_usuario/$',registro_usuario.as_view(),name='registro_usuario'),
	url(r'^crear_pregunta/$',crear_pregunta,name='crear_pregunta'),
	url(r'^anadir_opciones/$',anadir_opciones,name='anadir_opciones'),
	url(r'^lista_preguntas/$',lista_preguntas,name='lista_preguntas'),
	url(r'^contestar_pregunta2/(?P<pk>[-\w]+)/$',contestar_pregunta2,name='contestar_pregunta2'),

]

votos/urls.py
from django.conf.urls import include, url, patterns
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
admin.autodiscover()

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^',include('apps.voto.urls')),
    url(r'media/(?P<path>.*)$','django.views.static.serve',{'document_root':settings.MEDIA_ROOT,}),
) + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

apps/voto/models.py
from django.db import models
from django.contrib.auth.models import User
from django.core.validators import MaxValueValidator, MinValueValidator
from django.core.urlresolvers import reverse
from django.core.validators import MaxValueValidator, MinValueValidator,MaxValueValidator
from django.utils import timezone
from multiselectfield import MultiSelectField
import datetime
# Create your models here.
class QuerySet(models.QuerySet):
	def get_categoria(self):
		return self.nombre

class usuario(models.Model):
	user_perfil = models.OneToOneField(User, related_name="profile")
	nombre = models.CharField(max_length=64)
	edad = models.IntegerField()
	correo = models.EmailField()
	image = models.ImageField(upload_to='Perfiles/', blank=True, null=True)

	def __unicode__(self):
		return '%s'%(self.user_perfil)

class categoria(models.Model):
	id= models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=100)
	objects = QuerySet.as_manager()

	def __unicode__(self):
		return '%s' %(self.nombre)

class pregunta(models.Model):
	id = models.AutoField(primary_key=True)
	nombre = models.CharField(max_length=64)
	id_usuario = models.ForeignKey(usuario)
	id_categoria = models.ForeignKey(categoria,null=True,blank=True)
	creado = models.DateField(default=timezone.now,null=True,blank=True)


	def __unicode__(self):
		return '%s'%(self.nombre)

class opciones(models.Model):
	id = models.AutoField(primary_key=True)
	id_pregunta = models.ForeignKey(pregunta)
	opcion = models.CharField(max_length=64,null=True,blank=True)
	seleccionar = models.BooleanField(default=False)
	terminar = models.BooleanField(default=False)

	def __unicode__(self):
		return '%s'%(self.opcion)

class pregunta_opcion(models.Model):
	id = models.AutoField(primary_key=True)
	id_pregunta = models.ForeignKey(pregunta)
	id_opciones = models.ManyToManyField(opciones)

	def __unicode__(self):
		return u'%s'%(self.id)

	def get_opciones(self):
		return "\n".join([p.opcion for p in self.id_opciones.all()])
########################################################################### de aqui arriba funciona
class contestar_pregunta(models.Model):
	id = models.AutoField(primary_key=True)
	id_pregunta_opcion = models.ForeignKey(pregunta_opcion)
	id_opcion = models.ForeignKey(opciones,blank=True,null=True)

	def __unicode__(self):
		return '%s'%(self.id)

	#def get_opciones(self):
		return "\n".join([p.opcion for p in self.id_opcion.all()])

apps/voto/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import usuario, pregunta, opciones, pregunta_opcion, contestar_pregunta
from django.forms import ModelMultipleChoiceField
from django.forms import MultiWidget
from django.forms import widgets

class UserForm(UserCreationForm):
	nombre = forms.CharField(max_length=64)
	edad = forms.IntegerField()
	correo = forms.CharField(max_length=64)
	image= forms.ImageField()

class crear_preguntaForm(forms.ModelForm):
	class Meta:
		model = pregunta
		fields = '__all__'

class anadir_opcionesForm(forms.ModelForm):
	class Meta:
		model = opciones
		fields = '__all__'

class contestar_preguntaForm(forms.ModelForm):
	class Meta:
		model = contestar_pregunta
		fields = '__all__'

apps/voto/views.py
from django.shortcuts import render, get_object_or_404, redirect, render_to_response
from django.views.generic import FormView, CreateView, ListView,DetailView,UpdateView,DeleteView
from .forms import  UserForm, crear_preguntaForm, anadir_opcionesForm, contestar_preguntaForm
from django.core.urlresolvers import reverse_lazy
from django.http import HttpResponse
from django.http import HttpResponseRedirect
from .models import usuario, pregunta, opciones, pregunta_opcion, contestar_pregunta, categoria
from django.core.paginator import Paginator, EmptyPage, InvalidPage, PageNotAnInteger
from django.views.generic.detail import SingleObjectMixin
from django.contrib.auth.models import User
from django.views.generic.edit import ModelFormMixin
from decimal import Decimal
import datetime  

# Create your views here.
def index_view(request):
	pre = pregunta.objects.all()
	ctx = {'instance':pre}
	return render(request,"voto/index.html",ctx)

class registro_usuario(FormView):
	template_name = 'voto/registro_usuario.html'
	form_class = UserForm
	success_url = reverse_lazy('index_view')

	def form_valid(self,form):
		user = form.save()
		p = usuario()
		p.user_perfil = user
		p.nombre = form.cleaned_data['nombre']
		p.edad = form.cleaned_data['edad']
		p.correo = form.cleaned_data['correo']
		p.image = form.cleaned_data['image']
		p.save()
		return super(registro_usuario,self).form_valid(form)

def crear_pregunta(request):
	form = crear_preguntaForm(request.POST or None,request.FILES or None)
	c = categoria.objects.all()
	ctx = {'categorias':c}
	if form.is_valid():
		instance = form.save(commit=False)
		instance.creado = datetime.datetime.now()
		instance.save()
		return redirect('anadir_opciones')
	return render(request,'voto/crear_pregunta.html',ctx)

def anadir_opciones(request,pk=None):
	pregunta_get = pregunta.objects.latest('id')
	all_opciones = opciones.objects.filter(id_pregunta=pregunta_get)
	listaop = []

	for i in all_opciones:
		listaop.append(i)

	form = anadir_opcionesForm(request.POST or None)
	if form.is_valid():
		instance = form.save()
		instance.id_pregunta = pregunta.objects.get(id=request.POST['id_pregunta'])
		instance.opcion = request.POST['opcion']
		instance.save()
		if instance.terminar == True:
			p = pregunta_opcion()
			p.id_pregunta = instance.id_pregunta
			p.save()
			p.id_opciones = listaop
			return redirect('index_view')
	else:
		print "no valido"
	return render(request,'voto/anadir_opciones.html',{"object":pregunta_get})

def contestar_pregunta(request,pk=None):
	insta = get_object_or_404(pregunta,id=pk)
	preop = pregunta_opcion.objects.filter(id_pregunta = insta.id)
	ctx = {
			"object":insta,
			"list_objects":preop,
	}
	form = contestar_preguntaForm(request.POST or None)
	if form.is_valid():
		instance = form.save()
		print instance.id_opcion
		instance.save()
		return redirect('index_view')

	return render(request,'voto/contestar_pregunta.html',ctx)

templates/voto/anadir_opciones.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title>VotBit</title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,300,400,500" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/css/animsition.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.blue-light_blue.min.css">
    <link rel="stylesheet" href="{% static 'css/swipebox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>
<body>
	<div class="animsition">
		<!-- Page Content -->
		<main class="mdl-layout__content login-bg">
			<div class="login mdl-shadow--2dp"> <!-- card -->
				<div class="account-info mdl-color--primary">

					<div class="account-navigation"> <!-- top icons -->
						<a class="mdl-button mdl-js-button mdl-button--icon left" href="/">
							<i class="material-icons">arrow_back</i>
						</a>
						<button class="mdl-button mdl-js-button mdl-button--icon right">
							<i class="material-icons">close</i>
						</button>
						<div class="clr"></div>

						<div class="minilogo-account user1"></div> <!-- user -->
						<span>Ingresa con tu cuenta</span>
					</div>
				</div>
<div class="account-data"> <!-- text fields -->
	<form action="."  method="POST" enctype="multipart/form-data">
	{% csrf_token %}

		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo">
			<input class="mdl-textfield__input" type="text" name="opcion" id="id_opcion" />
			<label class="mdl-textfield__label">Ingrese una Opcion</label>
		</div>
		<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo">
			<input class="mdl-textfield__input" type="checkbox" name="terminar" id="id_terminar" />
			<label class="mdl-textfield__label">Terminar</label>
		</div>
    <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo">
      <input class="mdl-textfield__input" id="id_pregunt" value="{{object.id}}" name="id_pregunta" type="text" readonly="readonly"/ hidden="hidden">
      <label class="mdl-textfield__label">Pregunta</label>
    </div>
		<input type="submit" placeholder="Ingresar" name="action" id="id_registrar" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary right">
		<div class="clr"></div>
	</form>

</div>

</div>
</main>
</div>

<script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/js/jquery.animsition.js"></script>
<script src="{% static 'js/sweetalert.min.js' %}"></script>
<script src="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js"></script>
<script src="{% static 'js/jquery.swipebox.min.js' %}"></script>
<script src="{% static 'js/function.js' %}"></script>
</body>
</html>

{% endblock %}

templates/voto/contestar_pregunta.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title>VotBit</title>
    <meta name="description" content="">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,300,400,500" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/css/animsition.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.blue-light_blue.min.css">
    <link rel="stylesheet" href="{% static 'css/swipebox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

  <body>
    <div class="animsition">
      <!-- Page Content -->
      <main class="mdl-layout__content article">
        <div class="back">
          <a class="mdl-button mdl-js-button mdl-button--icon" href="/lista_preguntas">
            <i class="material-icons">arrow_back</i>
          </a>
        </div>
        <div class="article-header">
          <div class="gradient-container">
            <img src="{%static 'img/9.jpg' %}" alt="">
            <div class="overlay-gradient"></div>
          </div>
          <div class="card-header">
            <div class="contact-user bg-red"><span>J</span></div>
					{%for item in object_list %}
            <div class="card-autor">
							<h3>{{item.id_pregunta}}</h3>
							<span>{{item.creado}}</span>
            </div>
          </div>
        </div>

				{% endfor %}
        <div class="container">
					<form action="."  method="POST" enctype="multipart/form-data">
							{% csrf_token %}
							{%for item in object_list %}
								{{item.id_pregunta_opcion}}
									<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo">
								<input type="text" value="{{item.id}}" name="id_pregunta_opcion" hidden="hidden">
									<select class="mdl-textfield__input" multiple name="id_opcion">
									{%for item2 in item.id_opciones.all%}
										<!--<input type="checkbox" name="id_opcion" id="{{item2.id}}">
										<labe for="{{item2.id}}">{{item2.opcion}} {{item2.id}}<label>-->
											  <option value="{{item2.id}}">{{item2.opcion}} {{item2.id}}</option>
									{%endfor%}
									</select>
							{%endfor%}
							<br><br><br><br>
						<input type="submit" id="id_registrar" name="action" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary right">
					</form>
        </div>

        <div class="container">
          <span class="title title-counter">Comentarios</span><span class="light-text"></span>
          <div class="comments">
          </div>

        </div>
      </main>
    </div>



    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/js/jquery.animsition.js"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js"></script>
    <script src="{% static 'js/jquery.swipebox.min.js' %}"></script>
    <script src="{% static 'js/function.js' %}"></script>
  </body>
</html>

templates/voto/crear_pregunta.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title>VotBit</title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,300,400,500" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/css/animsition.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.blue-light_blue.min.css">
    <link rel="stylesheet" href="{% static 'css/swipebox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

  <body>
    <div class="animsition">
      <!-- Page Content -->
      <main class="mdl-layout__content login-bg">
        <div class="login mdl-shadow--2dp"> <!-- card -->
          <div class="account-info mdl-color--primary">

            <div class="account-navigation"> <!-- top icons -->
              <a class="mdl-button mdl-js-button mdl-button--icon left" href="/">
                <i class="material-icons">arrow_back</i>
              </a>
              <button class="mdl-button mdl-js-button mdl-button--icon right">
                <i class="material-icons">close</i>
              </button>
              <div class="clr"></div>

              <div class="minilogo-account user1"></div> <!-- user -->
              <span>Ingresa con tu cuenta</span>
            </div>
          </div>

          <div class="account-data"> <!-- text fields -->
            <form method='POST' autocomplete="off" action="." enctype="multipart/form-data">
            {% csrf_token %}
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo">
                <input class="mdl-textfield__input" id="id_nombre" name="nombre" type="text" />
                <label class="mdl-textfield__label">Pregunta</label>
              </div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo">
                <select class="mdl-textfield__input" name="categorias" id="id_categorias" />
                <option value="" class="mdl-textfield__label">Categoria</option>
                {% for a in categorias %}
                <option value="{{a.id}}">{{a.nombre}}</option>
                {% endfor %}
              </select>
              </div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" >
                <input class="mdl-textfield__input" type="text" name="id_usuario" id="id_usuario" value="{{user.profile.id}}" readonly="readonly" hidden="hidden"/>
                <label class="mdl-textfield__label" value="{{user.profile.id}}"></label>
              </div>
							<input type="submit" id="id_registrar" placeholder="Ingresar" name="action" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary right">
							<div class="clr"></div>
            </form>


          </div>

        </div>
      </main>
    </div>

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/js/jquery.animsition.js"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js"></script>
    <script src="{% static 'js/jquery.swipebox.min.js' %}"></script>
    <script src="{% static 'js/function.js' %}"></script>
  </body>
</html>

{%endblock%}

templates/voto/detalle_pregunta.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}

<center><h5>Conteste el examen correctamente</h5></center>
<div class="row">

    <form  action="." method="POST" enctype="multipart/form-data">
    	{% csrf_token %}
    	<!--{{form.as_p}}-->
    	<div class="container">
    		<div class="input-field col s6">
	    		<label>Numero de control</label>
		        <input type="text" value="{{user.alumno.n_control}}" name="id_alumno">
	   		</div>

	   		<input type="hidden"  value="{{object.id_examen}}" name="id_examen">
	   		<input type="hidden"  value="{{object.unidad}}" name="unidad">
	   		<input type="hidden"  value="{{object.id_materia.serie}}" name="id_materia">

	   		<!--{% for item in object_list %}
	   			{% for item2 in item.id_pregunta_respuesta.all%}
	   				<h5>{{item2.id_pregunta}}</h5>
	   				{% for item3 in ite2.id_respuesta.all %}
	   					<p>
					      <input type="checkbox" id="{{item3.id}}" name="id_respuesta"/>
					      <label for="{{item3.id}}">{{item3.nombre}}</label>
					    </p>
	   				{% endfor %}
	   			{% endfor %}
	   		{% endfor %}-->


	   		{% for item in object_list %}
	   			{% for item2 in item.id_pregunta_respuesta.all%}
		   		<div class="input-field col s12">
				    <select multiple name="id_respuesta">
				      <option value="" disabled selected>{{item2.id_pregunta}}</option>
				      {% for item3 in item2.id_respuesta.all %}
				      	<option value="{{item3.id}}">{{item3.nombre}}{{item3.id}}</option>
				      {%endfor%}
				    </select>
				    <input type="text" value="{{item2.id_pregunta_respuesta}}" name="id_pregunta_respuesta"/>
				</div>
				{%endfor%}
			{%endfor%}






	       <div class="row">
			    <button class="btn waves-effect waves-light col s12" type="submit" name="action" id="boton-guardar" name="boton-guardar">Enviar
			    </button>
	        </div>

    	</div>
    </form>
  </div>

{%endblock%}

templates/voto/index.html
{% extends 'base.html' %}
{% load staticfiles %}
{% block content %}
<div class="gradient-container index">
  <div class="article-header fullscreen bg-10">
    <div class="fullscreen-title valign-wrapper">
      <div class="valign">
        <h1 class="black">VotBit.</h1>
        <p class="black">– Solo decisiones rapidas –</p>
        <a href="/lista_preguntas" class="mdl-button mdl-js-button mdl-js-ripple-effect mdl-button--accent border">
          Leer Mas
        </a>
      </div>
    </div>
  </div>
</div>
<br><br><br>
{% if user.is_authenticated %}
{{user.profile.nombre}}
            {%for item in instance%}
              {{item.nombre}}<br>
              {{item.id_usuario}}
              <br><br>
            {%endfor%}
{%endif%}
{%endblock%}

templates/voto/registro_usuario.html
{% load staticfiles %}
<!DOCTYPE html>
<html class="no-js">
  <head>
    <meta charset="utf-8">
    <title>VotBit</title>
    <meta charset="utf-8">
    <meta name="description" content="">
    <meta name="HandheldFriendly" content="True">
    <meta name="MobileOptimized" content="320">
    <meta name="viewport" content="width=device-width, initial-scale=1, minimal-ui">

    <!-- Stylesheets -->
    <link rel="stylesheet" href="http://fonts.googleapis.com/css?family=Roboto:100,300,400,500" type="text/css">
    <link rel="stylesheet" href="https://fonts.googleapis.com/icon?family=Material+Icons">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/css/animsition.css">
    <link rel="stylesheet" type="text/css" href="{% static 'css/sweetalert.css' %}">
    <link rel="stylesheet" href="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.blue-light_blue.min.css">
    <link rel="stylesheet" href="{% static 'css/swipebox.min.css' %}">
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
  </head>

  <body>
    <div class="animsition">
      <!-- Page Content -->
      <main class="mdl-layout__content login-bg">
        <div class="login mdl-shadow--2dp"> <!-- card -->
          <div class="account-info mdl-color--primary">

            <div class="account-navigation"> <!-- top icons -->
              <a class="mdl-button mdl-js-button mdl-button--icon left" href="/">
                <i class="material-icons">arrow_back</i>
              </a>
              <button class="mdl-button mdl-js-button mdl-button--icon right">
                <i class="material-icons">close</i>
              </button>
              <div class="clr"></div>

              <div class="minilogo-account user1"></div> <!-- user -->
              <span>Ingresa con tu cuenta</span>
            </div>
          </div>

          <div class="account-data"> <!-- text fields -->
            <form method='POST' autocomplete="off" action="." enctype="multipart/form-data">
							{% csrf_token %}
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" style="padding:13px;">
                <input class="mdl-textfield__input" name="username" type="text" id="id_username"/>
                <label class="mdl-textfield__label">Nombre de Usuario</label>
              </div>
              <div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" style="padding:13px;">
                <input class="mdl-textfield__input" type="password" name="password1" id="id_password"/>
                <label class="mdl-textfield__label">Contraseña</label>
              </div>
							<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" style="padding:13px;">
								<input class="mdl-textfield__input" type="password" name="password2" id="id_password2"/>
								<label class="mdl-textfield__label">Repetir Contraseña</label>
							</div>
							<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" style="padding:13px;">
								<input class="mdl-textfield__input" type="text" name="nombre" id="id_nombre" />
								<label class="mdl-textfield__label">Nombre </label>
							</div>
							<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" style="padding:13px;">
								<input class="mdl-textfield__input" type="number" name="edad" id="id_edad"/>
								<label class="mdl-textfield__label">Edad </label>
							</div>
							<div class="mdl-textfield mdl-js-textfield mdl-textfield--floating-label textfield-demo" style="padding:13px;">
								<input class="mdl-textfield__input" type="text" name="correo" id="id_correo" />
								<label class="mdl-textfield__label">Correo </label>
							</div>
							<input type="submit" placeholder="Registrarse" name="action" id="id_registrar" class="mdl-button mdl-js-button mdl-button--raised mdl-js-ripple-effect mdl-button--primary right">
            <div class="clr"></div>
            </form>

          </div>

        </div>
      </main>
    </div>

    <script src="{% static 'js/jquery-2.1.4.min.js' %}"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/animsition/3.5.2/js/jquery.animsition.js"></script>
    <script src="{% static 'js/sweetalert.min.js' %}"></script>
    <script src="https://storage.googleapis.com/code.getmdl.io/1.0.2/material.min.js"></script>
    <script src="{% static 'js/jquery.swipebox.min.js' %}"></script>
    <script src="{% static 'js/function.js' %}"></script>
  </body>
</html>